### ISSUE TITLE
Improve quote stats

### ISSUE THREAD

**Issue by Lassi-T** [etkot/etkot-telegram-bot#23]
Quote stats currently shows way too much infomation and it spams the telegram chat. 

The /qs function could receive parameters for example "etkot" and then the qs message would only show quote stats for etkot members and leave out all the other random shit. In this a list of etkot member names should be added to the database. 
A function for adding new etkot members to the database should also be added in this case.

**Comment by HammerCar** [comment]
Maybe there should be groups that users can be added to. These groups could be created with a command and users added with another. The groups could also used for other commands if needed.

**Comment by Lassi-T** [comment]
A top _x_ option would also be nice

**Comment by HammerCar** [comment]
Fixed with an inline keyboard for navigating multiple pages of quote stats
